Portfolio mobile version (2nd milestone)
saqibjavaiddev/Portfolio-mobile-version-skeleton pull request #2
Opened 2022-05-26 11:53 UTC by saqibjavaiddev

For the second milestone in building my portfolio website, I created the mobile website section where I listed my portfolio projects. I build the work "Work" section and the "About myself" section. The learning objectives for this project are: 

- Understand how to parse a Figma design to create a UI.
- Use Flexbox to place elements in the page.
- Use CSS Grid to place elements in the page.
- Build a personal portfolio site.

2022-05-26 12:05 UTC, rindrajosia requested changes
Hi, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that some linters check are not successful. Keep in mind that Linter is there in order to help you to have a good code base quality. 

![linter](https://user-images.githubusercontent.com/58552748/170484496-f637f617-ca68-474f-89d2-95bf5f26de0e.jpg)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 12:11 UTC, saqibjavaiddev commented
Sorry I forgot about linters check, tried to undo submission but its was claimed

2022-05-26 14:30 UTC, muneebulrehman requested changes
Hi @saqibjavaiddev , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
- Please consider this review a chance to learn and improve your coding skills, because that is what you are here for.

## Highlights
- Good HTML structure
- Usage of semantic HTML tags.
- Good CSS.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Since you asked for the guide on how to fix linters in vs code, I suggest following this [link](https://github.com/microverseinc/linters-config/tree/master/html-css).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 15:50 UTC, saqibjavaiddev commented on index.html
> +          <img src="assets/img/work1.png" alt="Image project" class="project_image"/>
[muneebulrehman](https://github.com/muneebulrehman) Image width fixed

2022-05-26 15:50 UTC, saqibjavaiddev commented on index.html
> +              </ul>
Margin added

2022-05-26 15:52 UTC, saqibjavaiddev commented on index.html
> +        </section>
Margin bottom added

2022-05-26 15:52 UTC, saqibjavaiddev commented on index.html
> +        <section id="about_me">
border radius added

2022-05-26 15:54 UTC, saqibjavaiddev commented on index.html
> +            <div id="my_skills">
Added in lis form

2022-05-26 15:54 UTC, saqibjavaiddev commented on index.html
> +              <div id="languages_skills">
Done added

2022-05-26 15:54 UTC, saqibjavaiddev commented on index.html
> +              <div id="frameworks">
Added

2022-05-26 15:54 UTC, saqibjavaiddev commented on index.html
> +              <div id="frameworks1">
Added

2022-05-26 16:45 UTC, muneebulrehman approved these changes
Hi @saqibjavaiddev, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥳 
Congratulations! 🎉 

# Status: Approved

## Highlights
- Good documentation
- Linter checks are passing
- Amazing job following up with the previously raised issues.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-26 16:46 UTC, merged

2022-05-30 06:58 UTC, saqibjavaiddev commented
Hi [rindrajosia](https://github.com/rindrajosia) and [uneebulrehman](https://github.com/muneebulrehman) Please help me to setup linters on my vscode so I don't need to commit again and again to check linter errors or some tip and trick to fix on vscode directly